version: "1"

services:
  app:
    build:
      context: .
      args:
        DEV: "true"
    environment:
      - PYTHONPATH=/app
      - DEBUG=1
    ports:
      - "8080:8080"
    env_file:
      - path: ./.env
        required: true
    command: uvicorn main:app --reload --host 0.0.0.0 -port 8080
    volumes:
      - ./app:/app
    depends_on:
      - db
    links:
      - db
    working_dir: /
  
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB: ${DB_NAME}
      - POSTGRES_USER: ${DB_USER}
      - POSTGRES_PASSWORD: ${DB_PASSWORD}