version: "3.8"

services:
  app:
    build:
      context: .
    environment:
      PYTHONPATH: /app
      DEBUG: 1
    ports:
      - "8000:8000"
    env_file:
      - path: ./.env
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app
    depends_on:
      - db
    working_dir: /app
  
  db:
    image: postgres:15
    volumes:
      - backtrader_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  backtrader_data: